version: '3'

services:
    hedge:
        build:
          context: ./
          dockerfile: ./docker/Dockerfile    
        container_name: c-hedge        
        entrypoint: tail -f /dev/null
        cap_add:
          - NET_ADMIN
        networks:
          - n-hedge        
        volumes:
         - ./:/tmp/hedge
        read_only: false #Needed to make sudo sysctl work
        privileged: true #Needed to make sudo sysctl work

networks:
    n-hedge: