version: '3'

services:
    hedge_master:
        build:
          context: ./
          dockerfile: ./docker/Dockerfile    
        container_name: c-hedge-master
        entrypoint: /usr/sbin/sshd -D
        cap_add:
          - NET_ADMIN
        networks:
          - n-hedge        
        volumes:
         - ./:/tmp/hedge
        read_only: false #Needed to make sudo sysctl work
        privileged: true #Needed to make sudo sysctl work

    hedge_slave:
        build:
          context: ./
          dockerfile: ./docker/Dockerfile    
        container_name: c-hedge-slave
        entrypoint: /usr/sbin/sshd -D
        cap_add:
          - NET_ADMIN
        networks:
          - n-hedge
        volumes:
          - ./docker/c-hedge-slave.txt:/root/c-hedge-slave.txt
        read_only: false #Needed to make sudo sysctl work
        privileged: true #Needed to make sudo sysctl work

networks:
    n-hedge: